import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#121212",
    },
    scrollContainer: {
        padding: 20,
        paddingBottom: 40,
    },
    header: {
        marginBottom: 25,
        alignItems: "center",
        padding: 15,
        backgroundColor: "#1A1A1A",
        borderRadius: 10,
        borderLeftWidth: 4,
        borderLeftColor: "#8B0000",
        shadowColor: "#8B0000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    leagueTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#FFF",
        marginBottom: 5,
        textTransform: "uppercase",
        letterSpacing: 1,
    },
    matchDate: {
        fontSize: 15,
        color: "#8B0000",
        fontWeight: "600",
    },
    scoreContainer: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 30,
        backgroundColor: "#1E1E1E",
        padding: 25,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#333",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    teamContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    teamName: {
        fontSize: 18,
        fontWeight: "600",
        color: "#FFF",
        marginBottom: 12,
        textAlign: "center",
        width: "100%",
    },
    teamScore: {
        fontSize: 32,
        fontWeight: "bold",
        color: "#FFF",
        textShadowColor: "rgba(139, 0, 0, 0.5)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
        textAlign: "center",
        width: "100%",
    },
    vsContainer: {
        width: 60,
        alignItems: "center",
        justifyContent: "center",
    },
    vsText: {
        color: "#8B0000",
        fontWeight: "bold",
        fontSize: 18,
        textShadowColor: "rgba(139, 0, 0, 0.3)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
        textAlign: "center",
    },
    detailsContainer: {
        backgroundColor: "#1E1E1E",
        padding: 18,
        borderRadius: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: "#333",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    detailRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 10,
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: "#252525",
    },
    detailLabel: {
        color: "#8B0000",
        fontWeight: "600",
        fontSize: 15,
        letterSpacing: 0.5,
    },
    detailValue: {
        color: "#FFF",
        fontSize: 15,
        fontWeight: "500",
        maxWidth: "60%",
        textAlign: "right",
    },
    sectionTitle: {
        color: "#8B0000",
        fontWeight: "bold",
        fontSize: 18,
        marginBottom: 15,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: "#252525",
        letterSpacing: 0.5,
    },
    eventsContainer: {
        backgroundColor: "#1E1E1E",
        padding: 18,
        borderRadius: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: "#333",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    eventItem: {
        marginBottom: 10,
        paddingLeft: 10,
        borderLeftWidth: 2,
        borderLeftColor: "#8B0000",
    },
    eventText: {
        color: "#EEE",
        fontSize: 14,
        lineHeight: 20,
    },
    statsContainer: {
        backgroundColor: "#1E1E1E",
        padding: 18,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#333",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    statGroup: {
        marginBottom: 15,
        backgroundColor: "#252525",
        borderRadius: 8,
        padding: 12,
    },
    statGroupTitle: {
        color: "#8B0000",
        fontWeight: "bold",
        fontSize: 15,
        marginBottom: 8,
        paddingBottom: 4,
        borderBottomWidth: 1,
        borderBottomColor: "#333",
    },
    statItem: {
        marginBottom: 10,
        paddingLeft: 8,
        borderLeftWidth: 2,
        borderLeftColor: "#444",
    },
    statPlayer: {
        color: "#FFF",
        fontSize: 14,
        fontWeight: "500",
    },
    statAssist: {
        color: "#AAA",
        fontSize: 13,
        marginTop: 2,
        fontStyle: "italic",
    },
    statSubstitution: {
        color: "#AAA",
        fontSize: 13,
        marginTop: 2,
    },
    loadingIndicator: {
        marginVertical: 20,
    },
});
