import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#121212",
    },
    center: {
        justifyContent: "center",
        alignItems: "center",
    },
    loadingText: {
        color: "#FFF",
        marginTop: 15,
        fontSize: 16,
    },
    header: {
        padding: 20,
        backgroundColor: "#1A1A1A",
        borderBottomWidth: 1,
        borderBottomColor: "#8B0000",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        elevation: 5,
    },
    leagueTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#FFF",
        textAlign: "center",
        textTransform: "uppercase",
        letterSpacing: 1,
    },
    seasonTitle: {
        fontSize: 16,
        color: "#8B0000",
        textAlign: "center",
        marginTop: 5,
        fontWeight: "600",
    },
    resultsContainer: {
        flex: 1,
        paddingHorizontal: 15,
        paddingTop: 10,
    },
    matchesScroll: {
        flex: 1,
    },
    matchCard: {
        backgroundColor: "#1E1E1E",
        borderRadius: 10,
        padding: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: "#2A2A2A",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 2,
    },
    moreEventsText: {
        color: "#8B0000",
        fontSize: 12,
        marginTop: 5,
        fontStyle: "italic",
    },
    dateContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 12,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: "#333",
    },
    dateText: {
        color: "#8B0000",
        fontSize: 14,
        fontWeight: "600",
    },
    timeText: {
        color: "#AAA",
        fontSize: 14,
    },
    teamsContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 10,
    },
    teamContainer: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
    },
    teamName: {
        fontSize: 16,
        fontWeight: "600",
        color: "#FFF",
        flex: 1,
    },
    teamScore: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#FFF",
        marginHorizontal: 8,
        minWidth: 25,
        textAlign: "center",
    },
    vsText: {
        color: "#8B0000",
        fontWeight: "bold",
        fontSize: 14,
    },
    matchEvents: {
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: "#333",
    },
    eventsTitle: {
        color: "#8B0000",
        fontWeight: "600",
        marginBottom: 5,
    },
    eventText: {
        color: "#DDD",
        fontSize: 13,
        marginBottom: 3,
    },
    noMatchesContainer: {
        alignItems: "center",
        justifyContent: "center",
        padding: 30,
    },
    noMatchesText: {
        color: "#FFF",
        fontSize: 18,
        fontWeight: "600",
        marginBottom: 5,
    },
    noMatchesSubText: {
        color: "#AAA",
        fontSize: 14,
        textAlign: "center",
    },
    errorText: {
        color: "#FF3333",
        fontSize: 16,
        textAlign: "center",
        padding: 20,
    },
    retryButton: {
        marginTop: 15,
        paddingVertical: 10,
        paddingHorizontal: 20,
        backgroundColor: "#8B0000",
        borderRadius: 5,
    },
    retryText: {
        color: "#FFF",
        fontWeight: "bold",
    },
    showMoreButton: {
        padding: 12,
        backgroundColor: "#8B0000",
        borderRadius: 8,
        alignItems: "center",
        marginVertical: 10,
    },
    showMoreText: {
        color: "#FFF",
        fontWeight: "bold",
        fontSize: 16,
    },
    footer: {
        flexDirection: "row",
        justifyContent: "space-around",
        paddingVertical: 12,
        backgroundColor: "#1A1A1A",
        borderTopWidth: 1,
        borderTopColor: "#333",
    },
    footerItem: {
        paddingHorizontal: 10,
    },
    footerLinkText: {
        color: "#FFF",
        fontSize: 15,
        fontWeight: "500",
    },
});
