// StartUpStyles.js
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    scrollContainer: {
        flexGrow: 1,
        backgroundColor: "#121212",
    },
    container: {
        flex: 1,
        backgroundColor: "#121212",
        paddingHorizontal: 20,
        paddingTop: 30,
    },
    header: {
        fontSize: 28,
        fontWeight: "bold",
        color: "#d32f2f",
        marginBottom: 30,
        textAlign: "center",
        fontFamily: "sans-serif-condensed",
        textTransform: "uppercase",
        letterSpacing: 1.5,
    },
    tabContainer: {
        flexDirection: "row",
        marginBottom: 20,
        backgroundColor: "#1e1e1e",
        borderRadius: 10,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: "#2a2a2a",
    },
    tabButton: {
        flex: 1,
        paddingVertical: 15,
        alignItems: "center",
    },
    activeTab: {
        backgroundColor: "#8b0000",
    },
    tabText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#aaa",
    },
    activeTabText: {
        color: "#fff",
    },
    formContainer: {
        backgroundColor: "#1e1e1e",
        borderRadius: 10,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
        borderWidth: 1,
        borderColor: "#2a2a2a",
    },
    heading: {
        fontSize: 22,
        fontWeight: "bold",
        color: "#d32f2f",
        marginBottom: 25,
        textAlign: "center",
        textTransform: "uppercase",
        letterSpacing: 1,
    },
    input: {
        height: 50,
        borderColor: "#333",
        borderWidth: 1,
        marginBottom: 15,
        paddingHorizontal: 15,
        borderRadius: 8,
        fontSize: 16,
        backgroundColor: "#2a2a2a",
        color: "#fff",
    },
    button: {
        backgroundColor: "#8b0000",
        padding: 15,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 10,
        shadowColor: "#d32f2f",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 3,
        elevation: 4,
    },
    buttonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
        letterSpacing: 1,
    },
    leagueTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#d32f2f",
        textAlign: "center",
        marginBottom: 20,
        textTransform: "uppercase",
        letterSpacing: 2,
        fontFamily: "sans-serif-condensed",
    },
});
